### ISSUE TITLE
[WebToolsE2E][docs] When running the "Tutorial: Use .NET Aspire messaging integrations in ASP.NET Core" document using .NET CLI, there is an error.

### ISSUE THREAD

**Issue by v-reinawang** [dotnet/docs-aspire#2034]
### Describe the issue or suggestion
**Issue description**:
In "Tutorial: Use .NET Aspire messaging integrations in ASP.NET Core" doc, we need to make some updates to the instructions.
This issue only occurs when running the document using the .NET CLI development environment. There is no issue when using VS.

**Issue**:
Complete all the steps in the document using the .NET CLI development environment, the result obtained when [Run and test the app locally](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/messaging-integrations?branch=pr-en-us-1867&tabs=connection-string&pivots=dotnet-cli#run-and-test-the-app-locally) is an error, which is different from the result described in the document.
![Image](https://github.com/user-attachments/assets/cddcacdd-0ea7-4626-85be-07e916502c44)

 Hosting failed to start
2024-11-11T09:15:01       System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
2024-11-11T09:15:01          at System.ConsolePal.ReadKey(Boolean intercept)
2024-11-11T09:15:01          at AspireSample.WorkerService.Worker.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\v-reinawang\AspireSample\AspireSample.WorkerService\Worker.cs:line 31
2024-11-11T09:15:01          at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__14_1(IHostedService service, CancellationToken token)
2024-11-11T09:15:01          at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
![Image](https://github.com/user-attachments/assets/6c38fa19-a041-4d58-a0bb-c34466b42b74)

According to the error message, in Worker.cs file, Change "Console.ReadKey();" to "Console.Read();", but the expected result cannot be obtained. Display 'Stoped receiving messages' in console logs.
![Image](https://github.com/user-attachments/assets/cf476eb8-3f1d-4f0e-8edf-bef9d1c74249)

**Expected**:
After completing step 4 of the [Run and test the app locally](https://review.learn.microsoft.com/en-us/dotnet/aspire/messaging/messaging-integrations?branch=pr-en-us-1867&tabs=connection-string&pivots=dotnet-cli#run-and-test-the-app-locally) procedure, the corresponding information appears in the Console Log.
![Image](https://github.com/user-attachments/assets/83cee4cb-1224-48fe-ab86-98429e2ba2cd)

**Comment by v-reinawang** [comment]
Close this issue and use #2045 to track this bug.
